In [1]:
import numpy as np

In [3]:
L = [1, 2, 3]

In [4]:
A = np.array([1, 2, 3])

In [5]:
A

array([1, 2, 3])

In [6]:
L

[1, 2, 3]

In [7]:
A + A

array([2, 4, 6])

In [9]:
np.append(A, [4, 5])

array([1, 2, 3, 4, 5])

In [10]:
2*A

array([2, 4, 6])

In [11]:
2*L

[1, 2, 3, 1, 2, 3]

In [12]:
A**2

array([1, 4, 9])

In [13]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [14]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [15]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])