In [1]:
import numpy as np

In [3]:
# classic numpy array
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
# numpy array of zeros
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# numpy matrix (array) of zeros 10x10
Z = np.zeros((10, 10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
# numpy matrix (array) of ones 10x10
O = np.ones((10, 10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
# numpy matrix (array) of random numbers 10x10
R = np.random.random((10, 10))
R

array([[0.57088668, 0.74536053, 0.34995114, 0.03410958, 0.10280582,
        0.67316231, 0.32020024, 0.09375954, 0.50698972, 0.28855876],
       [0.75632069, 0.33994611, 0.03618514, 0.58645714, 0.53589636,
        0.5955787 , 0.3021027 , 0.11568088, 0.34251245, 0.67243144],
       [0.82774995, 0.68727272, 0.19273751, 0.20999907, 0.24568969,
        0.48681957, 0.29702083, 0.72190359, 0.63923927, 0.50008683],
       [0.86281691, 0.43817444, 0.00808159, 0.84060816, 0.93783262,
        0.59461297, 0.42340809, 0.80930056, 0.58607878, 0.88858439],
       [0.61440533, 0.86266682, 0.00509762, 0.55124944, 0.46705088,
        0.74475902, 0.1754736 , 0.89459834, 0.670482  , 0.56460832],
       [0.03042759, 0.75885994, 0.22016346, 0.55462263, 0.00478131,
        0.81293291, 0.96683017, 0.03017485, 0.37004221, 0.08807036],
       [0.38949644, 0.90847054, 0.54694772, 0.14610773, 0.07188159,
        0.33105806, 0.87813272, 0.85216736, 0.35057887, 0.43651751],
       [0.82420175, 0.19666487, 0.1419226

In [12]:
# numpy matrix (array) of random numbers with gaussian distribution 10x10
G = np.random.randn((10, 10))
G
# .randn doesnt interpret tuples, needs individual dimensions as agruments

TypeError: 'tuple' object cannot be interpreted as an integer

In [13]:
# correction for randn()
G = np.random.randn(10, 10)
G

array([[ 0.16645118, -0.30752358,  1.23544286,  0.45333071,  2.57201771,
         0.90694225,  0.20442987, -0.06475084,  0.70450352,  1.10847161],
       [-1.7795046 , -0.48223473, -0.03792041,  0.72528758, -0.13807624,
         0.05573555,  0.26200306,  0.37151936, -0.41100679, -0.87920129],
       [-0.62172243,  0.25570287,  0.96038835,  0.48248581, -1.27351207,
        -0.17550832,  1.01685686, -1.45532715, -0.08466982,  1.03238291],
       [-1.45817475,  0.26915552, -1.2943254 , -0.23960977,  0.51838518,
        -1.27134045,  0.52454059,  1.07755841,  1.21564941, -0.3562773 ],
       [-0.21248224, -1.58493331,  1.41648067,  0.08432536,  1.12920249,
        -2.15595838, -1.12541987, -0.46256293, -0.65899403,  0.86509156],
       [-0.94505294, -1.79943125, -0.66919497,  2.07428943, -1.2441447 ,
         0.96829326,  0.99269816,  0.3109508 , -0.32451326,  0.09670644],
       [-0.11543171, -0.30230365,  0.82521481,  0.86004833, -0.62285173,
        -1.05906116,  2.00944333,  0.42830198

In [14]:
# get the mean with numpy
G.mean()

-0.049642084749604506

In [15]:
# get the variance with numpy
G.var()

1.0223955623309902